########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################

from auto_grader.DNE_AutoGrader import AutoGrader
from auto_grader.DNE_Assignment import Assignment
from auto_grader.DNE_AutoGraderParam import AutoGraderParam
import numpy as np

assignments = []

# --------------------------------------------------------------------------
# Course Settings
# --------------------------------------------------------------------------

Param = AutoGraderParam()
Param.course_id = 0 # Replace with your course ID

# --------------------------------------------------------------------------
# Assignment 1 Assignment Information
# --------------------------------------------------------------------------

# Metadata for the assignment
title = ""
id = 0

# Define shapes
input_shapes = [(0,)]
output_shapes = [(0,)]

# Define input ranges
input_ranges = [np.array([[(None, None)]])]

# Define labels
input_labels = [""]
output_labels = [""]

# method or funciton to generate test data for
# If multiple functions and/or classes are to be tested then you can create a function or class that combines them.
class_to_evaluate = np
class_inputs = {"input_1": None}
function_to_evaluate = ""

assignments.append(Assignment(title, id, input_shapes, output_shapes, input_ranges, input_labels, output_labels, function_to_evaluate, class_to_evaluate=class_to_evaluate, class_inputs=class_inputs))

# --------------------------------------------------------------------------
# Create Auto Grading Object
# --------------------------------------------------------------------------
auto_grader = AutoGrader(assignments, Param)

########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################