#!/usr/bin/env python3
########################################################################################
#
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################
"""
Classroom 50 autograder entry point.

INSTRUCTOR: copy this file into your classroom50 config repository as

    <classroom>/autograders/<assignment>/autograder.py

and put a due_dates.csv beside it. Everything under that directory is bundled and
published to Pages, and the runner unpacks it before grading. Because this file only
bootstraps, it never needs reinstalling when the grading logic changes: the real work
lives in the solution repository's auto_grader submodule.

The runner executes this from inside the student's checkout, so the working directory
is the repository root. No secrets are used or needed.
"""

import os
import pathlib
import runpy
import subprocess
import sys

bundle = pathlib.Path(__file__).resolve().parent

# Point the grader at the due dates bundled beside this file. Keeping them here rather
# than in the student repository means a due date can be changed with a single push to
# the config repo, with no student repository to sync.
due_dates = bundle / "due_dates.csv"
if due_dates.is_file():
    os.environ["AUTOGRADER_DUE_DATES"] = str(due_dates)
    print(f"autograder: using due dates from {due_dates}")
else:
    print("autograder: no due_dates.csv in the bundle; no late penalties will be projected")

# The grader imports from the auto_grader submodule, which actions/checkout does not
# fetch by default.
subprocess.run(["git", "submodule", "update", "--init", "--recursive"], check=False)

# Install the assignment's dependencies.
subprocess.run([sys.executable, "-m", "pip", "install", "--quiet", "--upgrade", "pip"], check=False)
subprocess.run([sys.executable, "-m", "pip", "install", "--quiet", "-r", "requirements.txt"], check=False)

# Grade. This writes ./result.json and ./release-body.md for the runner to publish.
runpy.run_path("DNE_github_grade_on_push.py", run_name="__main__")

########################################################################################
#
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################
