########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
# 
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################

import os, sys

class HiddenPrints:
    def __enter__(self):
        self._original_stdout = sys.stdout
        sys.stdout = open(os.devnull, 'w')

    def __exit__(self, exc_type, exc_val, exc_tb):
        sys.stdout.close()
        sys.stdout = self._original_stdout

########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
# 
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################