########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
# 
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################

class AutoGraderParam:
    """
    Class to hold parameters for the Auto Grader.
    """
    # Course parameters
    # These must be set seperately for each couse
    course_id = None 

    # Autograding parameters
    iterations = int(1e4)
    tolerance = 1e-10  # Tolerance for checking outputs

    # Markdown formatting parameters
    total_average_report_blocks = int(10)

    # Grade parameters
    late_penalty_per_day = 5.0  # Points lost per day late
    late_penalty_floor = 50.0  # Minimum grade late penalty can reduce grade to

########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
# 
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################