########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
# 
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################

class AutoGraderParam:
    """
    Class to hold parameters for the Auto Grader.
    """
    # Course parameters
    course_id = None
    course = None  # The course name this run loaded, recorded in result.json
    
    # Repository parameters
    repo_name = "" 
    required_modules = []

    # Autograding parameters
    # Outputs match when they agree to within EITHER of these, as np.isclose does:
    #   |a - b| <= absolute_tolerance + relative_tolerance * |b|
    #
    # A relative term is what makes the comparison scale invariant. With absolute
    # tolerance alone, an output of magnitude 1e3 had to agree to thirteen significant
    # figures, which no two LAPACK builds will do; the grading data is generated on the
    # instructor's machine and compared on a Linux runner, and an EKF covariance or an
    # MRAC gain drifts further than that between the two. The absolute term stays as the
    # floor for outputs near zero, where a relative test means nothing.
    #
    # 1e-7 relative means "agree to seven significant figures" -- far beyond what a
    # wrong formula produces by accident, and comfortably above platform drift.
    tolerance = 1e-10           # absolute
    relative_tolerance = 1e-7   # relative

    # Markdown formatting parameters
    total_average_report_blocks = int(10)

    # Grade parameters
    late_penalty_per_day = 5.0  # Points lost per day late
    late_penalty_floor = 50.0  # Minimum grade late penalty can reduce grade to

########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
# 
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################