########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################

from datetime import datetime
from collections import defaultdict
import os
import traceback
from typing import List, Tuple
from .DNE_Assignment import Assignment
from .DNE_AutoGraderParam import AutoGraderParam
from .DNE_log import log
from .DNE_HiddenPrints import HiddenPrints
import argparse
from datetime import datetime, timezone
import shutil
import copy
try:
    import importlib
    import pickle
    import numpy as np
    import requests
except ImportError:
    log("Required packages not installed. Please copy over the autograder files into your workspace using 'AutoGrader.create_auto_grader_files()' then install the required packages by running 'pip install -r requirements.txt' (optiona virtual enviorment). Autograder is usable in the initial setup mode.", type="warning")

# enumeration for easier to read assignment info files
NOT_GRADED = None
CONSTANT_IO = None
SCALAR_IO = 1

class AutoGrader():
        DNE_text = ["########################################################################################",
                        "# ",
                        "#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ ",
                        "# |  _ \\  / _ \\      | \\ | | / _ \\ |_   _|     | ____||  _ \\ |_  _||_   _|",
                        "# | | | || | | |     |  \\| || | | |  | |       |  _|  | | | | |  |   | |  ",
                        "# | |_| || |_| |     | |\\  || |_| |  | |       | |___ | |_| | |  |   | |  ",
                        "# |____/  \\___/      |_| \\_| \\___/   |_|       |_____||____/ |_ __|  |_|  ",
                        "# ",
                        "# Do not edit this file. It is part of the system that grades your code submisions.",
                        "# The instructor will be notified if you submit an edited version of this file.",
                        "########################################################################################"]

        def __init__(self, assignments: List[Assignment], Param: AutoGraderParam):
            # Save assignments
            self.assignments = assignments

            # Save parameters
            self.Param = Param

            # Get file paths
            current_file_path = os.path.abspath(__file__)
            path_to_this_folder = os.path.dirname(current_file_path)
            path_to_root_folder = os.path.dirname(path_to_this_folder)
            private_data_folder = "_" + self.Param.repo_name + "_private_data"
            public_data_folder = self.Param.repo_name + "_public_data"
            self.public_data_file_path = os.path.join(path_to_root_folder, public_data_folder)
            self.private_data_file_path = os.path.join(path_to_root_folder, private_data_folder)

            self.log_file = os.path.join(path_to_root_folder,"_log.txt")
            self.markdown_file = os.path.join(path_to_root_folder, "_pull_request_comment.md")
            self.roster_file = os.path.join(self.private_data_file_path, '_roster.csv')

            self.create_pull_request_comment = True

        def run_and_record(self, assignment_index: int, output_data_file: str, comparison_file: str = None, verbose: bool = True
        ) -> str:

            # Delete the old output file if it exists
            with open(output_data_file, "w") as f:
                f.write(" ")

            # get the assignmnet information
            assignment = self.assignments[assignment_index]
            output_shapes = assignment.output_shapes
            output_labels = assignment.output_labels

            # Get the name of the class we're checking
            if assignment.class_to_evaluate is not None:
                class_text = f" in class '{assignment.class_to_evaluate.__name__}'"
            else:
                class_text = ""

            # Get the input data sets
            if comparison_file:
                if verbose: log(f"📂 Loading inputs from previous file: {comparison_file}")
                class_inputs, input_sets, _output_sets = self.load_data_from_pkl(comparison_file, self.Param.required_modules)
            else:
                if verbose: log(f"🎲 Generating {assignment.iterations} random input sets...")

                # For shorter lines of code
                input_ranges = assignment.input_ranges
                input_shapes = assignment.input_shapes
                input_labels = assignment.input_labels

                input_sets = []
                for _ in range(assignment.iterations):
                    inputs = {}
                    for input_number, (shape, label) in enumerate(zip(input_shapes, input_labels)):
                        if shape is CONSTANT_IO:
                            # If the shape is None, we don't generate an input
                            # for this label instead we assume that the range
                            # stores the value we should pass in.
                            inputs[label] = input_ranges[input_number]
                        else:
                            inputs[label] = self.generate_random_input(shape, input_ranges[input_number])

                    input_sets.append(inputs)

                # Class inputs
                class_inputs = assignment.class_inputs if assignment.class_inputs is not None else {}
            
            # Get the function to evaluate
            if isinstance(assignment.function_to_evaluate, str):
                # Create an instance of the class
                try:
                    with HiddenPrints():
                        instance = assignment.class_to_evaluate(**class_inputs)
                        function_to_evaluate = getattr(instance, assignment.function_to_evaluate)
                except Exception:
                    return f"Error instantiating the class '{assignment.class_to_evaluate.__name__}' for assignment '{assignment.title}'. Please check the class constructor. Error: \n\n" + traceback.format_exc()
            else:
                # If the function is already a callable, use it directly
                function_to_evaluate = assignment.function_to_evaluate
            

            # Evaluate function and collect results
            try:
                if verbose: log(f"⚙️ Evaluating function '{function_to_evaluate.__name__}'{class_text} with {len(input_sets)} input sets...")
                output_sets = []
                for inputs in input_sets:
                    # Ensure inputs match expected shapes
                    with HiddenPrints():
                        outputs = function_to_evaluate(**inputs)

                    if outputs is not None and not isinstance(outputs, tuple):
                        outputs = (outputs,)

                    # Confirm the number of outputs and output shapes match expected
                    # if the number of outputs does not match the expected number of outputs
                    if outputs is None or len(outputs) != len(output_shapes):
                        
                        if outputs is None:
                            number_of_outputs = 0
                        else:
                            number_of_outputs = len(outputs)
                        
                        return f"Function '{function_to_evaluate.__name__}'{class_text} returned {number_of_outputs} objects which does not match expected {len(output_shapes)} objects."
                    
                    # Check each output shape and mark for removal if the expected shape indicates it is not graded
                    marked_for_removal = []
                    for i, output in enumerate(outputs):
                        if output_shapes[i] is NOT_GRADED:
                            # If the output shape is not graded, we don't check the shape
                            # instead we remove the output from the list of outputs
                            marked_for_removal.append(i)
                        elif isinstance(output_shapes[i], tuple) and output.shape != output_shapes[i]:
                            return f"Function '{function_to_evaluate.__name__}' output {i} ('{output_labels[i]}') shape does not match expected. Got an object with the shape {output.shape}. Expected {output_shapes[i]}."
                        elif output_shapes[i] == SCALAR_IO:
                            try:
                                output = float(output)
                            except:
                                return f"Function '{function_to_evaluate.__name__}' output {i} ('{output_labels[i]}') is not numeric. Got an object of type {type(output)}."
                    
                    # Remove the outputs that are not graded 
                    # These are the outptus that are not graded.
                    outputs = [output for j, output in enumerate(outputs) if j not in marked_for_removal]
                    if len(outputs) != len(output_labels):
                        output_labels = [output_labels[j] for j in range(len(output_labels)) if j not in marked_for_removal]

                    # Save the outputs in a dictionary
                    dict_outputs = {label:output for label, output in zip(output_labels, outputs)}

                    output_sets.append(dict_outputs)
            except Exception:

                # If the function fails to execute, log the error
                return f"Function '{function_to_evaluate.__name__}'{class_text} execution failed. Please check the function implementation. Error: \n\n" + traceback.format_exc()
            else:
                # If the function executed successfully, log the success
                if verbose: log(f"Function '{function_to_evaluate.__name__}'{class_text} executed successfully.")

                # Save the input and output data to a pickel file
                self.save_data_to_pkl(class_inputs, input_sets, output_sets, output_data_file)

                # Log the successful save
                if verbose: log(f"Successfully saved data to {output_data_file}")
                
                return None
        
        def grade_file(self, comparison_file: str, test_file: str, tolerance: float) -> tuple[float, list[str], np.ndarray, np.ndarray, np.ndarray, np.ndarray]:

            # Load the pickel files
            _compare_class_inputs, _compare_input_sets, compare_output_sets = self.load_data_from_pkl(comparison_file, self.Param.required_modules)
            _test_class_inputs,    _test_input_sets,    test_output_sets    = self.load_data_from_pkl(      test_file, self.Param.required_modules)
    
            # 1. Build column_labels: "variable_name[indexes]" for each key and each element in the array
            column_labels = []
            output_keys = list(compare_output_sets[0].keys())
            output_shapes = {k: compare_output_sets[0][k].shape for k in output_keys}

            # Generate all (key, index_tuple) pairs
            column_tuples = []
            for k in output_keys:
                shape = output_shapes[k]
                for idx in np.ndindex(shape):
                    column_labels.append(f"{k}[{','.join(map(str, idx))}]")
                    column_tuples.append((k, idx))

            # 2. Build the 2D arrays
            def flatten_outputs(output_sets):
                arr = np.empty((len(output_sets), len(column_labels)), dtype=float)
                for i, outputs in enumerate(output_sets):
                    for j, (k, idx) in enumerate(column_tuples):
                        arr[i, j] = outputs[k][idx]
                return arr

            sol_values = flatten_outputs(compare_output_sets)
            test_values = flatten_outputs(test_output_sets)

            # Compare values with tolerance
            matches = np.isclose(sol_values, test_values, rtol=0, atol=tolerance)
            error = np.abs(sol_values - test_values)
            error[matches] = 0  # Set matches to 0 to acount for tolerance

            # Calculate statistics
            total_entries = matches.size
            total_iterations = sol_values.shape[0]
            correct_total = matches.sum()
            correct_by_column = matches.sum(axis=0, keepdims=True)
            percent_correct = correct_total / total_entries
            percent_correct_by_column = correct_by_column / total_iterations

            # Calculate average error by column only considering non-matching entries
            # Only consider non-matching entries for average error
            with np.errstate(invalid='ignore'):
                sum_error = np.sum(error, axis=0, keepdims=True)
                count_non_matches = np.sum(~matches, axis=0, keepdims=True)
                # Avoid division by zero: set average error to 0 where all entries match
                average_error_by_column = np.where(count_non_matches == 0, 0, sum_error / count_non_matches)
            
            # Bin the error for the error plot
            data_points_per_block = int(np.floor(sol_values.shape[0]/ self.Param.total_average_report_blocks))
            binned_error = np.zeros((self.Param.total_average_report_blocks, sol_values.shape[1]))
            for i in range(self.Param.total_average_report_blocks):
                mask = np.vstack((np.zeros((i*data_points_per_block,1)), np.ones((data_points_per_block,1)), np.zeros((sol_values.shape[0]-(i+1)*data_points_per_block,1))))
                bin_data = error*mask
                binned_error[i,:] = np.sum(bin_data, axis=0)

            # Calculate the iteration of first error by column
            iteration_of_first_error_by_column = np.argmax(error > tolerance, axis=0, keepdims=True)
            for i in range(iteration_of_first_error_by_column.shape[1]):
                if iteration_of_first_error_by_column[0, i] == 0 and matches[0, i]:
                    iteration_of_first_error_by_column[0, i] = -1

            return percent_correct, column_labels, percent_correct_by_column, average_error_by_column, iteration_of_first_error_by_column, binned_error

        def format_markdown_header(self):
            if self.create_pull_request_comment:
                with open(self.markdown_file, "w") as f:
                    print("", file=f)
                    print("# ⚙️ Autograder Feedback ⚙️ #", file=f)
                    print("", file=f)
                    print("⏰ " + self.dtStylish(datetime.now(),"Autograded on %A, %B {th}, %Y at %H:%M:%S"), file=f)
                    print("", file=f)
                    # print("---", file=f)
                    print("", file=f)

        def format_markdown_section(self, assignment_title, final_score, max_score, column_labels=None, percent_correct_by_column=None, average_error_by_column=None, iteration_of_first_error_by_column=None, binned_error=None, tolerance=1e-10, error_string=None):

            if self.create_pull_request_comment:
                with open(self.markdown_file, "a") as f:
                    # Print assignment header
                    print("", file=f)
                    print(f"## 📝 {assignment_title}", file=f)
                    print("", file=f)

                    # Print the grade
                    if abs(final_score - max_score) < tolerance:
                        print(f"### ✅ grade: $\\color{{{self.rgb_to_hex(40,150,90)}}}{{\\mathbf{{{final_score:.2f}}}}}$/{int(max_score)}", file=f)
                    else:
                        print(f"### ❌ grade: $\\color{{{self.rgb_to_hex(186,28,33)}}}{{\\mathbf{{{final_score:.2f}}}}}$/{int(max_score)}", file=f)
                    print("", file=f)

                    # If there was no error, print the detailed breakdown
                    if error_string is None:
                        print("### 📊 Detailed Breakdown of Results", file=f)
                        print("", file=f)
                        if len(column_labels) <= 20:
                            print("| Output | Tests Passed | Average Error | 1st Error | Error plot |", file=f)
                            print("| --- | --- | --- | --- | --- |", file=f)
                            
                            # for each function output
                            for col, column_name in enumerate(column_labels):
                                # Generate a row in the table
                                first_error = iteration_of_first_error_by_column[0, col] if iteration_of_first_error_by_column[0, col] != -1 else "None"
                                format_string = f"| {column_name} | {percent_correct_by_column[0, col]:.2%} | {average_error_by_column[0, col]:.2e} | {first_error}"
                                format_string += "|$"

                                # Add the error plot
                                for test_case in binned_error[:, col]:
                                    if test_case < tolerance:
                                        format_string += f"\\color{{{self.rgb_to_hex(0,255,0)}}}{{▬}}"
                                    else:
                                        color = int(255-255 * (test_case / np.max(binned_error[:, col])))
                                        format_string += f"\\color{{{self.rgb_to_hex(255,color,color)}}}{{▬}}"
                                    # Add the test case error values
                                format_string += "$|"

                                # Plot the row
                                print(format_string, file=f)
                        else:

                            print("Too many outputs to display in table format", file=f)
                            print("", file=f)

                            # Percent correct
                            print(f"- **Percent Correct:** {np.mean(percent_correct_by_column)}", file=f)

                            # Exclude correct values from average error calculation
                            average_error = np.mean(average_error_by_column[average_error_by_column != 0]) if np.any(average_error_by_column!=0) else 0.0
                            print(f"- **Average Error:** {average_error}", file=f)

                            # Only consider values which are not -1
                            valid_first_errors = iteration_of_first_error_by_column[iteration_of_first_error_by_column != -1]
                            if valid_first_errors.size > 0:
                                min_first_error = np.min(valid_first_errors)
                            else:
                                min_first_error = "None"
                            print(f"- **Test Case of 1st Error:** {min_first_error}", file=f)
                    else:
                        # If there was an error, print the error message
                        print("### ❌ Error", file=f)
                        print("", file=f)
                        print("Autograding of this assignment failed due to an error given below. Please check the error message below and fix the code.", file=f)
                        print("", file=f)
                        print("> " + error_string, file=f)

                    # Assignment footer
                    print("", file=f)

        def format_markdown_footer(self, canvas_submissoin_status, run_locally: bool = True):
            if self.create_pull_request_comment:
                with open(self.markdown_file, "a") as f:
                    print("", file=f)
                    print("---", file=f)
                    print("", file=f)
                    print("**1st Error** Indicates which test case first returned incorrect results. 'None' means no error occured. When debugging, retrying these inputs is a good place to start.", file=f)
                    print("", file=f)
                    print(f"**Error Plot** Each block shows average error over several test cases. Green indicates all correct results, red indicates some incorrect results. " +
                        "The darker the shade of red, the larger the error. This can be useful to see if the error is following a pattern (indicating an issue " +
                        "with persistent variables) or if it is random (indicating an issue with the algorithm).", file=f)
                    print("", file=f)
                    if canvas_submissoin_status:
                        print("📤 Grades have been submitted to Canvas. Please check your grade on Canvas to confirm that it has been recorded correctly.", file=f)
                    else:
                        if run_locally:
                            print("⚠️ This feedback is provided for information purposes only. These grades have NOT been submitted to Canvas. To submit to Canvas you must push this code to GitHub.", file=f)
                        else:
                            print("❌ There was an error submiting grades to Canvas. Please ensure you have provided the correct Github user ID to the Canvas survey. Speak with the instructor to resolve this issue.", file=f)
                    print("", file=f)
                    print("**⚙️ End of Autograder Feedback ⚙️**", file=f)
                    print("", file=f)

        def run_auto_gradeing(self, assignment_indexes: list[int] = None, check_or_grade: str = "check", 
                              verbose: bool = True, markdown_header_footer: bool = True) -> list[float]:

            # Get the assignments to generate data for
            if assignment_indexes is None:
                assignment_indexes = range(len(self.assignments))

            # Markdown header
            if markdown_header_footer:
                self.format_markdown_header()

            grades = [0.0]*len(assignment_indexes)
            for i,a in enumerate(assignment_indexes):

                # Assignment title
                assignment_title = self.assignments[a].title

                # Create the file names
                check_file_name = f"DNE_{assignment_title}_checker_data.pkl"
                grade_file_name = f"_{assignment_title}_grader_data.pkl"
                test_file_name = f"_{assignment_title}_test_data.pkl"
                
                # Create the full file paths
                check_file_path = os.path.join(self.public_data_file_path, check_file_name)
                grade_file_path = os.path.join(self.private_data_file_path, grade_file_name)
                test_file_path = os.path.join(self.public_data_file_path, test_file_name)

                if check_or_grade == "check":
                    comparison_file = check_file_path
                elif check_or_grade == "grade":
                    comparison_file = grade_file_path

                # Generate the test data for the assignment
                if verbose: log(f"Generating TEST data for {self.assignments[a].title}...")
                error_string = self.run_and_record(a, output_data_file = test_file_path, comparison_file = comparison_file, verbose=verbose)
                if error_string is not None:
                    # If there was an error, log it and continue to the next assignment
                    log(error_string, type="error")
                    final_score = 0.0
                    log(f"{final_score}/{self.assignments[a].max_score}", type="grade")
                    self.format_markdown_section(assignment_title, final_score, self.assignments[a].max_score, error_string=error_string)
                    continue

                # grade the test data against the comparison file
                if verbose: log(f"Grading {self.assignments[a].title} by evaluating {test_file_path} against {comparison_file}...")
                percent_correct, column_labels, percent_correct_by_column, average_error_by_column, iteration_of_first_error_by_column, binned_error \
                    = self.grade_file(comparison_file, test_file_path, self.Param.tolerance)

                # Calculate the final score
                final_score = percent_correct * self.assignments[a].max_score
                grades[i] = final_score
                
                # Log the results
                log(f"Grading {self.assignments[a].title} completed.")
                log(f"{final_score}/{self.assignments[a].max_score}", type="grade")

                # Generate the markdown section for the assignment
                self.format_markdown_section(assignment_title, final_score, self.assignments[a].max_score, column_labels=column_labels, percent_correct_by_column=percent_correct_by_column, average_error_by_column=average_error_by_column, iteration_of_first_error_by_column=iteration_of_first_error_by_column, binned_error=binned_error, tolerance=self.Param.tolerance)

            # Markdown footer
            if markdown_header_footer:
                self.format_markdown_footer(canvas_submissoin_status=False, run_locally=(check_or_grade == "check"))

            return grades

        def create_assignment_files(self, assignment_indexes: list[int] = None, overwrite: bool = False):

            # Warn students not to use this method
            log("This method is not for students. It will override important autograding files with junk data. If you accidentally run it then you need to use git to reset those files.", type="warning")

            # Get the assignments to generate data for
            if assignment_indexes is None:
                assignment_indexes = range(len(self.assignments))

            for a in assignment_indexes:
                # Assignment title
                assignment_title = self.assignments[a].title

                # Create the file names
                check_file_name = f"DNE_{assignment_title}_checker_data.pkl"
                grade_file_name = f"_{assignment_title}_grader_data.pkl"
                # test_file_name = f"{assignment_title}_test_data.pkl"
                
                # Create the full file paths
                check_file_path = os.path.join(self.public_data_file_path, check_file_name)
                grade_file_path = os.path.join(self.private_data_file_path, grade_file_name)
                # test_file_path = os.path.join(self.public_data_file_path, test_file_name)

                log(f"Generating CHECK data for {self.assignments[a].title}...")
                error_string = self.run_and_record(a, check_file_path)
                if error_string is not None:
                    # If there was an error, log it and continue to the next assignment
                    log(error_string, type="error")
                    raise Exception(f"Error generating CHECK data for {self.assignments[a].title}. Please check the error message below. \n {error_string}")
                
                log(f"Generating GRADE data for {self.assignments[a].title}...")
                error_string = self.run_and_record(a, grade_file_path)
                if error_string is not None:
                    # If there was an error, log it and continue to the next assignment
                    log(error_string, type="error")
                    raise Exception(f"Error generating GRADE data for {self.assignments[a].title}. Please check the error message below. \n {error_string}")
                
            # Get the current file path
            auto_grader_path = os.path.dirname(os.path.abspath(__file__))
            root_file_path = os.path.dirname(auto_grader_path)

            # Create the check file
            check_file = os.path.join(root_file_path, f"run_code_checker.py")
            if not os.path.exists(check_file) or overwrite:
                with open(check_file, "w") as f:
                    print("# select an assignment to check from the list below", file=f)
                    print("assignment_to_check = '" + self.assignments[0].title + "'", file=f)
                    print("", file=f)
                    print("# Set this flag to True to check all assignments simultaneously", file=f)
                    print("check_all_assignments = False", file=f)
                    print("", file=f)
                    print("list_of_assignments = [", file=f)
                    for a in assignment_indexes:
                        print(f"    '{self.assignments[a].title}',", file=f)
                    print("]", file=f)
                    print("", file=f)
                    print("# Import the auto grader", file=f)
                    print("from DNE_assignment_info import auto_grader", file=f)
                    print("", file=f)
                    print("if check_all_assignments:", file=f)
                    print("    # Evaluate all assignments", file=f)
                    print("    import numpy as np", file=f)
                    print("    auto_grader.run_auto_gradeing(assignment_indexes = np.arange(len(list_of_assignments)), verbose=False)", file=f)
                    print("else:", file=f)
                    print("    # Find the index of the assignment to check", file=f)
                    print("    assignment_to_check_index = list_of_assignments.index(assignment_to_check)", file=f)
                    print("", file=f)
                    print("    # Evaluate the specific assignment", file=f)
                    print("    auto_grader.run_auto_gradeing(assignment_indexes = [assignment_to_check_index])", file=f)
                    
        def post_grades(self):

            # Warn students not to use this method
            log("This method is not for students. It runs when you push your code to Github. It will not run locally.", type="warning")

            # Argument parsing
            try:
                with HiddenPrints():
                    parser = argparse.ArgumentParser()
                    parser.add_argument('--canvas_api_token', type=str, required=True,  help=argparse.SUPPRESS)
                    parser.add_argument('--github_actor', type=str, required=True,  help=argparse.SUPPRESS)
                    parser.print_usage = lambda: None  # Suppress help message
                    args = parser.parse_args()
            except:
                log("Secret grading information not provided. You have likely run the wrong script." + 
                    " The file 'DNE_github_grade_on_push.py' is run automatically on github (with the appropriate secret grading information) after you push your code." + 
                    " Students should use the 'check.py' scripts to check their work.", type="error")
                return

            # Mark that the pull request comment should be created
            self.create_pull_request_comment = True

            # Pull request comment header
            self.format_markdown_header()

            # Grading
            grades = self.run_auto_gradeing(check_or_grade="grade", markdown_header_footer=False)

            # Default to submission success
            canvas_submissoin_status = True

            # Get Canvas student ID
            try:
                with open(self.roster_file, "r") as f:
                    header = f.readline().strip().split(",")
                    github_idx = header.index("github_username")
                    canvas_idx = header.index("canvas_student_id")
                    student_id = None
                    for line in f:
                        fields = line.strip().split(",")
                        if fields[github_idx] == args.github_actor:
                            student_id = fields[canvas_idx]
                            break
                    if student_id is None or student_id == "":
                        log(f"No Canvas Student ID found for Github user {args.github_actor}. Please confirm you submitted the correct Github username to Canvas.", type="error")
                        exit(1)
                    student_id = int(student_id)
            except:
                log(f"Error reading the roster file {self.roster_file}. Please ensure the '_roster.csv' file exists and is formatted correctly.", type="error")
            

            # Posting grades to Canvas
            for i, (assignment, grade) in enumerate(zip(self.assignments, grades)):

                # -------------------------------
                # Setup
                # -------------------------------

                # Log the action
                log(f"Posting grade {grade} for student {student_id} on assignment {assignment.id} ('{assignment.title}') in course {self.Param.course_id}")

                # Configuration
                api_url = 'https://utahtech.instructure.com//api/v1'
                api_token = args.canvas_api_token # Canvas API token - secret
                course_id = self.Param.course_id # Replace with your course ID
                assignment_id = assignment.id # Replace with your assignment ID
                student_id = student_id # Replace with the Canvas user ID of the student
                late_penalty_per_day = self.Param.late_penalty_per_day # Points lost per day late
                late_grade_floor = self.Param.late_penalty_floor  # Minimum grade to assign

                # Extract rubric criterion IDs if they exist
                assignment_id, rubric_criterion = assignment_id.split(" ", 1) if " " in assignment_id else (assignment_id, None)

                # -------------------------------
                # Retrive assignment and submission details
                # -------------------------------

                # Headers
                headers = {
                    'Authorization': f'Bearer {api_token}',
                    'Content-Type': 'application/json'
                }

                # Request to Retrieve Assignment Details
                url = f"{api_url}/courses/{course_id}/assignments/{assignment_id}"
                assignment_response = requests.get(url, headers=headers)

                # Request to Retrieve Submission Details
                url = f"{api_url}/courses/{course_id}/assignments/{assignment_id}/submissions/{student_id}"
                submission_response = requests.get(url, headers=headers, params={"include[]": "rubric_assessment"})

                # -------------------------------
                # Unpack responses
                # -------------------------------    

                # Unpack the assignment
                if assignment_response.status_code != 200:
                    log(f"Failed to retrieve assignment. Status Code: {response.status_code} Response: {response.text}", type="error")
                    canvas_submissoin_status = False
                    continue
                else:
                    assignment_json = assignment_response.json()

                # Unpack the submission
                if submission_response.status_code != 200:
                    log(f"Failed to retrieve previous submission. Status Code: {response.status_code} Response: {response.text}", type="warning")
                    previous_grade = 0
                    submission = None
                else: 
                    submission = submission_response.json()
                    if rubric_criterion is None:
                        grade_value = submission.get('grade')
                        previous_grade = float(grade_value) if grade_value is not None else 0.0 
                    else:
                        # If rubric criterion is specified, get the grade from the rubric
                        rubric = submission.get('rubric_assessment', {})
                        criterion = rubric.get(rubric_criterion, {})
                        grade_value = criterion.get('points', 0.0)
                        previous_grade = float(grade_value) if grade_value is not None else 0.0
                    log(f"Previous submission grade: {previous_grade}")

                # -------------------------------
                # Late Penalty Calculation
                # -------------------------------

                # Apply late penalty if applicable
                due_at = assignment_json.get('due_at')

                if due_at:
                    # Convert due date string to datetime object
                    due_date = datetime.strptime(due_at, '%Y-%m-%dT%H:%M:%SZ')
                    due_date = due_date.replace(tzinfo=timezone.utc)

                    # Get current UTC time
                    current_time = datetime.now(timezone.utc)

                    # Calculate days since due date
                    delta = (current_time - due_date).days

                    if delta <= 0:
                        log("The assignment is submitted before the due date.")
                    else:
                        log(f"The assignment is {delta+1} day(s) overdue (rounded up).", type="warning")
                        
                        # Apply late penalty
                        new_grade = grade
                        if new_grade > late_grade_floor/100.0*assignment.max_score:
                            new_grade = max(late_grade_floor/100.0*assignment.max_score, 
                                            grade - (late_penalty_per_day/100.0*assignment.max_score * (delta+1)))
                        log(f"Late penalty: {grade - new_grade} points", type="warning")
                        log(f"New grade after applying late penalty: {new_grade}", type="warning")
                        grade = new_grade

                else:
                    log("This assignment has no due date.")

                # -------------------------------
                # Don't lower the grade
                # -------------------------------

                if (previous_grade is not None and previous_grade >= grade) or (previous_grade is None and grade == 0):
                    log(f"Previous grade {previous_grade} is equal to or higher than the new grade {grade}. NOT posting the new grade.", type="warning")
                    continue

                # -------------------------------
                # Update the rubric or score
                # -------------------------------

                if rubric_criterion is None:
                    # Payload
                    payload = {
                        'submission': {
                            'posted_grade': grade
                        },
                        'comment': {
                            'text_comment': f"grade posted via AutoGrader on {self.dtStylish(datetime.now(), '%A, %B {th}, %Y at %H:%M:%S')}.",
                        }
                    }
                else:
                    rubric = submission.get("rubric_assessment", {})
                    rubric[rubric_criterion] = {"points": grade, "comments": f"grade posted via AutoGrader on {self.dtStylish(datetime.now(), '%A, %B {th}, %Y at %H:%M:%S')}."}
                    score_list = [criterion.get("points", None) for criterion in rubric.values()]
                    # Check if there is a missing score in score_list
                    if any(s is None for s in score_list):
                        payload = {
                                'rubric_assessment': rubric
                        }
                    else:
                        TOTAL_SCORE = sum(score_list)
                        payload = {
                                'posted_grade': TOTAL_SCORE,
                                'rubric_assessment': rubric
                        }

                # -------------------------------
                # Post Grade
                # -------------------------------

                # POST Request
                url = f"{api_url}/courses/{course_id}/assignments/{assignment_id}/submissions/{student_id}"
                response = requests.put(url, headers=headers, json=payload)

                # Response Check
                if response.status_code == 200:
                    log(f"✅ grade successfully posted.")
                else:
                    log(f"Failed to post grade. Status Code: {response.status_code} Response: {response.text}", type="error")
                    canvas_submissoin_status = False
            
            # Pull request comment footer
            self.format_markdown_footer(canvas_submissoin_status=canvas_submissoin_status)

        @staticmethod
        def dtStylish(dt,f):
            ordinal = str(dt.day)+("th" if 4<=dt.day%100<=20 else {1:"st",2:"nd",3:"rd"}.get(dt.day%10, "th"))
            return dt.strftime(f).replace("{th}", ordinal)

        @staticmethod
        def rgb_to_hex(r, g, b):
            """
            Converts RGB color values to a hexadecimal string.

            Args:
                r (int): Red component (0-255).
                g (int): Green component (0-255).
                b (int): Blue component (0-255).

            Returns:
                str: Hexadecimal color string (e.g., '#RRGGBB').
            """
            # Ensure values are within the valid range (0-255)
            r = max(0, min(255, r))
            g = max(0, min(255, g))
            b = max(0, min(255, b))

            # Use f-strings for concise formatting (Python 3.6+)
            return f'#{r:02X}{g:02X}{b:02X}'

        @staticmethod
        def save_data_to_pkl(class_inputs: dict[str, dict | np.ndarray],
                               input_sets: list[dict[str, np.ndarray]], 
                               output_sets: list[dict[str, np.ndarray]], 
                               data_file: str):
            """
            Save the data to pickle file.
            """

            # Combine the information into a single dictionary
            combined_data = {
                "class_inputs": class_inputs,
                "input_sets": input_sets,
                "output_sets": output_sets
            }

            # Save the combined data to a pickle file
            with open(data_file, "wb") as f:
                pickle.dump(combined_data, f)

        @staticmethod
        def generate_random_input(shape: tuple | int, ranges: np.ndarray | tuple) -> np.ndarray:
            if isinstance(shape, tuple):
                if ranges.shape[0:len(shape)] != shape:
                    log(f"Input shape {shape} does not match ranges shape {ranges.shape}.", type="error")
                low = ranges[...,0]
                high = ranges[...,1]
                return np.random.uniform(low, high)
            elif shape == SCALAR_IO:
                low = ranges[0]
                high = ranges[1]
                return np.random.uniform(low, high)
            
        @staticmethod
        def load_data_from_pkl(data_file: str, required_modules) -> tuple[dict[str, np.ndarray],list[dict[str, np.ndarray]],list[dict[str, np.ndarray]]]:
            """
            Load pickle file data

            Args:
                data_file: path to pickle file

            Returns:
                class_inputs: dict, maps input keyword (i.e. a label) to np.ndarray of correct shape
                input_sets: list of dicts, each dict maps input keyword (i.e. a label) to np.ndarray of correct shape
                output_sets: list of dicts, each dict maps output keyword (i.e. a label) to np.ndarray of correct shape
            """

            # Load the data from the pickle file
            try:
                if required_modules:
                    for module in required_modules:
                        importlib.import_module(module)

                with open(data_file, "rb") as f:
                    data = pickle.load(f)
            except FileNotFoundError:
                log(f"Pickel file {data_file} not found. Please ensure the file exists and is in the correct format.", type="error")
                return {}, [], []
            
            # Confrim the data is formatted correctly
            if not all(key in data for key in ["class_inputs", "input_sets", "output_sets"]):
                log(f"Data file {data_file} is in the wrong format. Expected keys: 'class_inputs', 'input_sets', 'output_sets'. Found keys: {data.keys()}", type="error")
                return {}, [], []
            
            # Unpack the data
            class_inputs = data.get("class_inputs", {})
            input_sets = data.get("input_sets", [])
            output_sets = data.get("output_sets", [])

            return class_inputs, input_sets, output_sets

        @staticmethod
        def create_auto_grader_files(repo_name: str = None, overwrite: bool = False):
            """
            Create the necessary files for the auto grader to work.
            This includes the private grader folder and the roster file.
            """

            # Warn students not to use this method
            log("This method is not for students. It will override important autograding files with junk data. If you accidentally run it then you need to use git to reset those files.", type="warning")

            # Get the current file path
            auto_grader_path = os.path.dirname(os.path.abspath(__file__))
            root_file_path = os.path.dirname(auto_grader_path)
            if repo_name is None:
                root_folder_name = os.path.basename(root_file_path)
            else:
                root_folder_name = repo_name
            private_data_folder = "_" + root_folder_name + "_private_data"
            public_data_folder = root_folder_name + "_public_data"
            private_data_path = os.path.join(root_file_path, private_data_folder)
            public_data_path = os.path.join(root_file_path, public_data_folder)
            workflow_file_path = os.path.join(root_file_path, ".github", "workflows")

            # ---------------------------------------------------------------
            # Create the private grader folder and files
            # ---------------------------------------------------------------

            # Create the private grader folder if it does not exist
            if not os.path.exists(private_data_path):
                os.makedirs(private_data_path)
            if not os.path.exists(public_data_folder):
                os.makedirs(public_data_folder)

            # Create the roster file if it does not exist
            roster_file = os.path.join(private_data_folder, "_roster.csv")
            if not os.path.exists(roster_file) or overwrite:
                with open(roster_file, "w") as f:
                    print("github_username,canvas_student_id", file=f)
            
            # ---------------------------------------------------------------
            # Create the root folder and files
            # ---------------------------------------------------------------

            # Create the generator file if it does not exist
            gen_file = os.path.join(root_file_path, "_create_assignment_files.py")
            if not os.path.exists(gen_file) or overwrite:
                with open(gen_file, "w") as f:
                    print("from DNE_assignment_info import auto_grader", file=f)
                    print("auto_grader.create_assignment_files()", file=f)

            # Create the post grades file if it does not exist
            post_file = os.path.join(root_file_path, "DNE_github_grade_on_push.py")
            if not os.path.exists(post_file) or overwrite:
                with open(post_file, "w") as f:
                    for line in AutoGrader.DNE_text:
                        print(line, file=f)
                    print("from DNE_assignment_info import auto_grader", file=f)
                    print("auto_grader.post_grades()", file=f)
                    for line in AutoGrader.DNE_text:
                        print(line, file=f)

            # Initilize the assignment info file if it does not exist
            assignment_info_template_file = os.path.join(auto_grader_path, "DNE_assignment_info_template.py")
            assignment_info_file = os.path.join(root_file_path, "DNE_assignment_info.py")
            if not os.path.exists(assignment_info_file) or overwrite:
                shutil.copy(assignment_info_template_file, assignment_info_file)

            # Initilize the workflow file if it does not exist
            provided_file = os.path.join(auto_grader_path, "DNE_classroom_template.yml")
            installed_file = os.path.join(workflow_file_path, "classroom.yml")
            if not os.path.exists(workflow_file_path):
                os.makedirs(workflow_file_path)
            if not os.path.exists(installed_file) or overwrite:
                shutil.copy(provided_file, installed_file)

            # Initilize the requirements file if it does not exist
            provided_file = os.path.join(auto_grader_path, "DNE_requirements_template.txt")
            installed_file = os.path.join(root_file_path, "requirements.txt")
            if not os.path.exists(installed_file) or overwrite:
                shutil.copy(provided_file, installed_file)
            
########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################