########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################

from datetime import datetime
from collections import defaultdict
import os
import traceback
from typing import List, Tuple
from .DNE_Assignment import Assignment
from .DNE_AutoGraderParam import AutoGraderParam
from .DNE_log import log
from .DNE_HiddenPrints import HiddenPrints
import argparse
from datetime import datetime, timezone
import shutil
try:
    import importlib
    import pickle
    import numpy as np
    import requests
except ImportError:
    log("Required packages not installed. Please copy over the autograder files into your workspace using 'AutoGrader.create_auto_grader_files()' then install the required packages by running 'pip install -r requirements.txt' (optiona virtual enviorment). Autograder is usable in the initial setup mode.", type="warning")

class AutoGrader():
        DNE_text = ["########################################################################################",
                        "# ",
                        "#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ ",
                        "# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|",
                        "# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  ",
                        "# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  ",
                        "# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  ",
                        "# ",
                        "# Do not edit this file. It is part of the system that grades your code submisions.",
                        "# The instructor will be notified if you submit an edited version of this file.",
                        "########################################################################################"]

        def __init__(self, assignments: List[Assignment], Param: AutoGraderParam):
            # Save assignments
            self.assignments = assignments

            # Save parameters
            self.Param = Param

            # Get file paths
            current_file_path = os.path.abspath(__file__)
            path_to_this_folder = os.path.dirname(current_file_path)
            path_to_root_folder = os.path.dirname(path_to_this_folder)
            private_data_folder = "_" + self.Param.repo_name + "_private_data"
            public_data_folder = self.Param.repo_name + "_public_data"
            self.public_data_file_path = os.path.join(path_to_root_folder, public_data_folder)
            self.private_data_file_path = os.path.join(path_to_root_folder, private_data_folder)

            self.log_file = os.path.join(path_to_root_folder,"_log.txt")
            self.markdown_file = os.path.join(path_to_root_folder, "_pull_request_comment.md")
            self.roster_file = os.path.join(self.private_data_file_path, '_roster.csv')

            self.create_pull_request_comment = False
            

        def convert_objects_to_functions(self, assignment_indexes: list[int] = None):
            """
            Convert class assignments to functions that can be run.
            This is useful for running the autograder on a function instead of a class.
            """

            for i in assignment_indexes:
                if isinstance(self.assignments[i].function_to_evaluate, str):
                    # Create an instance of the class
                    instance = self.assignments[i].class_to_evaluate(**self.assignments[i].class_inputs)

                    # Convert the method to a function
                    self.assignments[i].function_to_evaluate = getattr(instance, self.assignments[i].function_to_evaluate)
                    self.assignments[i].class_to_evaluate = self.assignments[i].class_to_evaluate.__name__
                    self.assignments[i].class_inputs = None

        def run_and_record(self, assignment_index: int, output_data_file: str, comparison_file: str = None,
        ) -> str:

            # Delete the old output file if it exists
            with open(output_data_file, "w") as f:
                f.write(" ")

            # get the assignmnet information
            assignment = self.assignments[assignment_index]
            function_to_evaluate = assignment.function_to_evaluate
            output_shapes = assignment.output_shapes
            output_labels = assignment.output_labels

            # Get the name of the class we're checking
            if assignment.class_to_evaluate is not None:
                class_text = f" in class '{assignment.class_to_evaluate}'"
            else:
                class_text = ""

            # Get the input data sets
            if comparison_file:
                log(f"📂 Loading inputs from previous file: {comparison_file}")
                _class_inputs, input_sets, _output_sets = self.load_data_from_pkl(comparison_file, self.Param.required_modules)
            else:
                log(f"🎲 Generating {self.Param.iterations} random input sets...")

                # For shorter lines of code
                input_ranges = assignment.input_ranges
                input_shapes = assignment.input_shapes
                input_labels = assignment.input_labels

                input_sets = []
                for _ in range(self.Param.iterations):
                    inputs = {
                        label: self.generate_random_input(shape, input_ranges[input_number])
                        for input_number, (shape, label) 
                        in enumerate(zip(input_shapes, input_labels))
                    }
                    input_sets.append(inputs)

            # Evaluate function and collect results
            try:
                output_sets = []
                for inputs in input_sets:
                    # Ensure inputs match expected shapes
                    with HiddenPrints():
                        outputs = function_to_evaluate(**inputs)

                    if outputs is not None and not isinstance(outputs, tuple):
                        outputs = (outputs,)

                    # Confirm the number of outputs and output shapes match expected
                    # if the number of outputs does not match the expected number of outputs
                    if outputs is None or len(outputs) != len(output_shapes):
                        
                        if outputs is None:
                            number_of_outputs = 0
                        else:
                            number_of_outputs = len(outputs)
                        
                        return f"Function '{function_to_evaluate.__name__}'{class_text} returned {number_of_outputs} objects which does not match expected {len(output_shapes)} objects."
                    
                    # Check each output shape
                    for i, output in enumerate(outputs):
                        if output.shape != output_shapes[i]:
                            return f"Function '{function_to_evaluate.__name__}' output {i} ('{output_labels[i]}') shape does not match expected. Got an object with the shape {output.shape}. Expected {output_shapes[i]}."
                    
                    # Save the outputs in a dictionary
                    dict_outputs = {label:output for label, output in zip(output_labels, outputs)}

                    output_sets.append(dict_outputs)
            except Exception:

                # If the function fails to execute, log the error
                return f"Function '{function_to_evaluate.__name__}'{class_text} execution failed. Please check the function implementation. Error: \n\n" + traceback.format_exc()
            else:
                # If the function executed successfully, log the success
                log(f"Function '{function_to_evaluate.__name__}'{class_text} executed successfully.")

                # Save the input and output data to a pickel file
                self.save_data_to_pkl(assignment.class_inputs, input_sets, output_sets, output_data_file)

                # Log the successful save
                log(f"Successfully saved data to {output_data_file}")
                
                return None
        
        def grade_file(self, comparison_file: str, test_file: str, tolerance: float) -> tuple[float, list[str], np.ndarray, np.ndarray, np.ndarray, np.ndarray]:

            # Load the pickel files
            _compare_class_inputs, _compare_input_sets, compare_output_sets = self.load_data_from_pkl(comparison_file, self.Param.required_modules)
            _test_class_inputs,    _test_input_sets,    test_output_sets    = self.load_data_from_pkl(      test_file, self.Param.required_modules)
    
            # 1. Build column_labels: "variable_name[indexes]" for each key and each element in the array
            column_labels = []
            output_keys = list(compare_output_sets[0].keys())
            output_shapes = {k: compare_output_sets[0][k].shape for k in output_keys}

            # Generate all (key, index_tuple) pairs
            column_tuples = []
            for k in output_keys:
                shape = output_shapes[k]
                for idx in np.ndindex(shape):
                    column_labels.append(f"{k}[{','.join(map(str, idx))}]")
                    column_tuples.append((k, idx))

            # 2. Build the 2D arrays
            def flatten_outputs(output_sets):
                arr = np.empty((len(output_sets), len(column_labels)), dtype=float)
                for i, outputs in enumerate(output_sets):
                    for j, (k, idx) in enumerate(column_tuples):
                        arr[i, j] = outputs[k][idx]
                return arr

            sol_values = flatten_outputs(compare_output_sets)
            test_values = flatten_outputs(test_output_sets)

            # Compare values with tolerance
            matches = np.isclose(sol_values, test_values, rtol=0, atol=tolerance)
            error = np.abs(sol_values - test_values)
            error[matches] = 0  # Set matches to 0 to acount for tolerance

            # Calculate statistics
            total_entries = matches.size
            total_iterations = sol_values.shape[0]
            correct_total = matches.sum()
            correct_by_column = matches.sum(axis=0, keepdims=True)
            average_error_by_column = np.mean(error, axis=0, keepdims=True)
            percent_correct = correct_total / total_entries
            percent_correct_by_column = correct_by_column / total_iterations
            
            # Bin the error for the error plot
            data_points_per_block = int(np.floor(sol_values.shape[0]/ self.Param.total_average_report_blocks))
            binned_error = np.zeros((self.Param.total_average_report_blocks, sol_values.shape[1]))
            for i in range(self.Param.total_average_report_blocks):
                mask = np.vstack((np.zeros((i*data_points_per_block,1)), np.ones((data_points_per_block,1)), np.zeros((sol_values.shape[0]-(i+1)*data_points_per_block,1))))
                bin_data = error*mask
                binned_error[i,:] = np.sum(bin_data, axis=0)

            # Calculate the iteration of first error by column
            iteration_of_first_error_by_column = np.argmax(error > tolerance, axis=0, keepdims=True)
            for i in range(iteration_of_first_error_by_column.shape[1]):
                if iteration_of_first_error_by_column[0, i] == 0 and matches[0, i]:
                    iteration_of_first_error_by_column[0, i] = -1

            return percent_correct, column_labels, percent_correct_by_column, average_error_by_column, iteration_of_first_error_by_column, binned_error

        def format_markdown_header(self):
            if self.create_pull_request_comment:
                with open(self.markdown_file, "w") as f:
                    print("", file=f)
                    print("# :gear: Autograder Feedback :gear: #", file=f)
                    print("", file=f)
                    print(":alarm_clock: " + self.dtStylish(datetime.now(),"Autograded on %A, %B {th}, %Y at %H:%M:%S"), file=f)
                    print("", file=f)
                    print("---", file=f)
                    print("", file=f)

        def format_markdown_section(self, assignment_title, final_score, max_score, column_labels=None, percent_correct_by_column=None, average_error_by_column=None, iteration_of_first_error_by_column=None, binned_error=None, tolerance=1e-10, error_string=None):

            if self.create_pull_request_comment:
                with open(self.markdown_file, "a") as f:
                    # Print assignment header
                    print("", file=f)
                    print(f"## :memo: {assignment_title}", file=f)
                    print("", file=f)

                    # Print the grade
                    if abs(final_score - max_score) < tolerance:
                        print(f"### :white_check_mark: Grade: $\color{{{self.rgb_to_hex(40,150,90)}}}{{\mathbf{{{final_score:.2f}}}}}$/{int(max_score)}", file=f)
                    else:
                        print(f"### :x: Grade: $\color{{{self.rgb_to_hex(186,28,33)}}}{{\mathbf{{{final_score:.2f}}}}}$/{int(max_score)}", file=f)
                    print("", file=f)

                    # If there was no error, print the detailed breakdown
                    if error_string is None:
                        print("### :bar_chart: Detailed Breakdown of Results", file=f)
                        print("", file=f)
                        print("| Output | Tests Passed | Average Error | 1st Error | Error plot |", file=f)
                        print("| --- | --- | --- | --- | --- |", file=f)
                        
                        # for each function output
                        for col, column_name in enumerate(column_labels):
                            # Generate a row in the table
                            format_string = f"| {column_name} | {percent_correct_by_column[0, col]:.2%} | {average_error_by_column[0, col]:.2e} | {iteration_of_first_error_by_column[0, col]}"
                            format_string += "|$"

                            # Add the error plot
                            for test_case in binned_error[:, col]:
                                if test_case < tolerance:
                                    format_string += f"\color{{{self.rgb_to_hex(0,255,0)}}}{{▬}}"
                                else:
                                    color = int(255-255 * (test_case / np.max(binned_error[:, col])))
                                    format_string += f"\color{{{self.rgb_to_hex(255,color,color)}}}{{▬}}"
                                # Add the test case error values
                            format_string += "$|"

                            # Plot the row
                            print(format_string, file=f)
                    else:
                        # If there was an error, print the error message
                        print("### :x: Error", file=f)
                        print("", file=f)
                        print("Autograding of this assignment failed due to an error given below. Please check the error message below and fix the code.", file=f)
                        print("", file=f)
                        print("> " + error_string, file=f)

                    # Assignment footer
                    print("", file=f)
                    print("---", file=f)
                    print("", file=f)

        def format_markdown_footer(self, canvas_submissoin_status):
            if self.create_pull_request_comment:
                with open(self.markdown_file, "a") as f:
                    print("", file=f)
                    print("- **1st Error** Indicates which test case first returned incorrect results. -1 means no error occured. When debugging, retrying these inputs is a good place to start.", file=f)
                    print(f"- **Error Plot** Each block shows average error over {int(round(self.Param.iterations/self.Param.total_average_report_blocks))} test cases. Green indicates all correct results, red indicates some incorrect results. " +
                        "The darker the shade of red, the larger the error. This can be useful to see if the error is following a pattern (indicating an issue " +
                        "with persistent variables) or if it is random (indicating an issue with the algorithm).", file=f)
                    print("", file=f)
                    if canvas_submissoin_status:
                        print("### :outbox_tray: Grades have been submitted to Canvas. Please check your grade on Canvas to confirm that it has been recorded correctly.", file=f)
                        print("", file=f)
                    else:
                        print("### :warning: There was an error submiting grades to Canvas. Please ensure you have provided the correct Github user ID to the Canvas survey. Speak with the instructor to resolve this issue.", file=f)
                        print("", file=f)
                    print("Please confirm your results by running the tests locally.", file=f)
                    print("", file=f)
                    print("**:gear: End of Autograder Feedback :gear:**", file=f)
                    print("", file=f)

        def run_auto_gradeing(self, assignment_indexes: list[int] = None, check_or_grade: str = "check") -> list[float]:

            # Get the assignments to generate data for
            if assignment_indexes is None:
                assignment_indexes = range(len(self.assignments))

            grades = [0.0]*len(assignment_indexes)
            for i,a in enumerate(assignment_indexes):

                # Assignment title
                assignment_title = self.assignments[a].title

                # Convert class assignments to functions if needed
                try:
                    self.convert_objects_to_functions([a])
                except Exception:
                    error_string = f"Error instantiating the class '{self.assignments[a].class_to_evaluate.__name__}' for assignment '{self.assignments[a].title}'. Please check the class constructor. Error: \n\n" + traceback.format_exc()
                    log(error_string, type="error")
                    final_score = 0.0
                    log(final_score, type="grade")
                    self.format_markdown_section(assignment_title, final_score, self.assignments[a].max_score, error_string=error_string)
                    continue

                # Create the file names
                check_file_name = f"DNE_{assignment_title}_checker_data.pkl"
                grade_file_name = f"_{assignment_title}_grader_data.pkl"
                test_file_name = f"_{assignment_title}_test_data.pkl"
                
                # Create the full file paths
                check_file_path = os.path.join(self.public_data_file_path, check_file_name)
                grade_file_path = os.path.join(self.private_data_file_path, grade_file_name)
                test_file_path = os.path.join(self.public_data_file_path, test_file_name)

                if check_or_grade == "check":
                    comparison_file = check_file_path
                elif check_or_grade == "grade":
                    comparison_file = grade_file_path

                # Generate the test data for the assignment
                log(f"Generating TEST data for {self.assignments[a].title}...")
                error_string = self.run_and_record(a, output_data_file = test_file_path, comparison_file = comparison_file)
                if error_string is not None:
                    # If there was an error, log it and continue to the next assignment
                    log(error_string, type="error")
                    final_score = 0.0
                    log(final_score, type="grade")
                    self.format_markdown_section(assignment_title, final_score, self.assignments[a].max_score, error_string=error_string)
                    continue

                # Grade the test data against the comparison file
                log(f"Grading {self.assignments[a].title} by evaluating {test_file_path} against {comparison_file}...")
                percent_correct, column_labels, percent_correct_by_column, average_error_by_column, iteration_of_first_error_by_column, binned_error \
                    = self.grade_file(comparison_file, test_file_path, self.Param.tolerance)

                # Calculate the final score
                final_score = percent_correct * self.assignments[a].max_score
                grades[i] = final_score
                
                # Log the results
                log(f"Grading {self.assignments[a].title} completed.")
                log(final_score, type="grade")

                # Generate the markdown section for the assignment
                self.format_markdown_section(assignment_title, final_score, self.assignments[a].max_score, column_labels=column_labels, percent_correct_by_column=percent_correct_by_column, average_error_by_column=average_error_by_column, iteration_of_first_error_by_column=iteration_of_first_error_by_column, binned_error=binned_error, tolerance=self.Param.tolerance)

            return grades

        def create_assignment_files(self, assignment_indexes: list[int] = None, overwrite: bool = False):

            # Warn students not to use this method
            log("This method is not for students. It will override important autograding files with junk data. If you accidentally run it then you need to use git to reset those files.", type="warning")

            # Get the assignments to generate data for
            if assignment_indexes is None:
                assignment_indexes = range(len(self.assignments))

            # Convert class assignments to functions if needed
            self.convert_objects_to_functions(assignment_indexes)

            for a in assignment_indexes:
                # Assignment title
                assignment_title = self.assignments[a].title

                # Create the file names
                check_file_name = f"DNE_{assignment_title}_checker_data.pkl"
                grade_file_name = f"_{assignment_title}_grader_data.pkl"
                # test_file_name = f"{assignment_title}_test_data.pkl"
                
                # Create the full file paths
                check_file_path = os.path.join(self.public_data_file_path, check_file_name)
                grade_file_path = os.path.join(self.private_data_file_path, grade_file_name)
                # test_file_path = os.path.join(self.public_data_file_path, test_file_name)

                log(f"Generating CHECK data for {self.assignments[a].title}...")
                error_string = self.run_and_record(a, check_file_path)
                if error_string is not None:
                    # If there was an error, log it and continue to the next assignment
                    log(error_string, type="error")
                    raise Exception(f"Error generating CHECK data for {self.assignments[a].title}. Please check the error message below. \n {error_string}")
                
                log(f"Generating GRADE data for {self.assignments[a].title}...")
                error_string = self.run_and_record(a, grade_file_path)
                if error_string is not None:
                    # If there was an error, log it and continue to the next assignment
                    log(error_string, type="error")
                    raise Exception(f"Error generating CHECK data for {self.assignments[a].title}. Please check the error message below. \n {error_string}")
                
            # Get the current file path
            auto_grader_path = os.path.dirname(os.path.abspath(__file__))
            root_file_path = os.path.dirname(auto_grader_path)

            # Create the check file
            check_file = os.path.join(root_file_path, f"DNE_run_code_checker.py")
            if not os.path.exists(check_file) or overwrite:
                with open(check_file, "w") as f:
                    print("# select an assignment to check from the list below", file=f)
                    print("assignment_to_check = '" + self.assignments[0].title + "'", file=f)
                    print("", file=f)
                    print("list_of_assignments = [", file=f)
                    for a in assignment_indexes:
                        print(f"    '{self.assignments[a].title}',", file=f)
                    print("]", file=f)
                    print("", file=f)
                    print("# Find the index of the assignment to check", file=f)
                    print("assignment_to_check_index = list_of_assignments.index(assignment_to_check)", file=f)
                    print("", file=f)
                    print("# Import the auto grader and run it", file=f)
                    print("from DNE_assignment_info import auto_grader", file=f)
                    print(f"auto_grader.run_auto_gradeing(assignment_indexes = [assignment_to_check_index])", file=f)

        def post_grades(self):

            # Warn students not to use this method
            log("This method is not for students. It runs when you push your code to Github. It will not run locally.", type="warning")

            # Argument parsing
            try:
                with HiddenPrints():
                    parser = argparse.ArgumentParser()
                    parser.add_argument('--canvas_api_token', type=str, required=True,  help=argparse.SUPPRESS)
                    parser.add_argument('--github_actor', type=str, required=True,  help=argparse.SUPPRESS)
                    parser.print_usage = lambda: None  # Suppress help message
                    args = parser.parse_args()
            except:
                log("Secret grading information not provided. You have likely run the wrong script." + 
                    " The file 'DNE_github_grade_on_push.py' is run automatically on github (with the appropriate secret grading information) after you push your code." + 
                    " Students should use the 'check.py' scripts to check their work.", type="error")
                return

            # Mark that the pull request comment should be created
            self.create_pull_request_comment = True

            # Pull request comment header
            self.format_markdown_header()

            # Grading
            grades = self.run_auto_gradeing(check_or_grade="grade")

            # Default to submission success
            canvas_submissoin_status = True

            # Get Canvas student ID
            try:
                with open(self.roster_file, "r") as f:
                    header = f.readline().strip().split(",")
                    github_idx = header.index("github_username")
                    canvas_idx = header.index("canvas_student_id")
                    student_id = None
                    for line in f:
                        fields = line.strip().split(",")
                        if fields[github_idx] == args.github_actor:
                            student_id = fields[canvas_idx]
                            break
                    if student_id is None or student_id == "":
                        log(f"No Canvas Student ID found for Github user {args.github_actor}. Please confirm you submitted the correct Github username to Canvas.", type="error")
                        exit(1)
                    student_id = int(student_id)
            except:
                log(f"Error reading the roster file {self.roster_file}. Please ensure the '_roster.csv' file exists and is formatted correctly.", type="error")
            

            # Posting grades to Canvas
            for i, (assignment, grade) in enumerate(zip(self.assignments, grades)):
                # Log the action
                log(f"Posting grade {grade} for student {student_id} on assignment {assignment.id} ('{assignment.title}') in course {self.Param.course_id}")

                # Configuration
                API_URL = 'https://utahtech.instructure.com//api/v1'
                API_TOKEN = args.canvas_api_token # Canvas API token - secret
                COURSE_ID = self.Param.course_id # Replace with your course ID
                ASSIGNMENT_ID = assignment.id # Replace with your assignment ID
                STUDENT_ID = student_id # Replace with the Canvas user ID of the student
                GRADE = grade #90.0  # Grade you want to assign
                LATE_PENALTY = self.Param.late_penalty_per_day # Points lost per day late
                LATE_GRADE_FLOOR = self.Param.late_penalty_floor  # Minimum grade to assign

                # Extract rubric criterion IDs if they exist
                ASSIGNMENT_ID, RUBRIC_CRITERION = ASSIGNMENT_ID.split("_", 1) if "_" in ASSIGNMENT_ID else (ASSIGNMENT_ID, None)
                if RUBRIC_CRITERION is not None:
                    RUBRIC_CRITERION = "_" + RUBRIC_CRITERION

                # -------------------------------
                # Check for late penalty and previous score
                # -------------------------------

                # Headers
                headers = {
                    'Authorization': f'Bearer {API_TOKEN}',
                    'Content-Type': 'application/json'
                }

                # API Endpoint
                url = f"{API_URL}/courses/{COURSE_ID}/assignments/{ASSIGNMENT_ID}"
                # Request to Retrieve Assignment Details
                assignment_response = requests.get(url, headers=headers)

                # API Endpoint
                url = f"{API_URL}/courses/{COURSE_ID}/assignments/{ASSIGNMENT_ID}/submissions/{STUDENT_ID}"
                # Request to Retrieve Assignment Details
                submission_response = requests.get(url, headers=headers, params={"include[]": "rubric_assessment"})

                # Check if the request was successful
                if assignment_response.status_code == 200:
                    assignment_json = assignment_response.json()

                    # Apply late penalty if applicable
                    due_at = assignment_json.get('due_at')

                    if due_at:
                        # Convert due date string to datetime object
                        due_date = datetime.strptime(due_at, '%Y-%m-%dT%H:%M:%SZ')
                        due_date = due_date.replace(tzinfo=timezone.utc)

                        # Get current UTC time
                        current_time = datetime.now(timezone.utc)

                        # Calculate days since due date
                        delta = (current_time - due_date).days

                        if delta <= 0:
                            log("The assignment is submitted before the due date.")
                        else:
                            log(f"The assignment is {delta+1} day(s) overdue (rounded up).", type="warning")
                            
                            # Apply late penalty
                            NEW_GRADE = GRADE
                            if NEW_GRADE > LATE_GRADE_FLOOR/100.0*assignment.max_score:
                                NEW_GRADE = max(LATE_GRADE_FLOOR/100.0*assignment.max_score, GRADE - (LATE_PENALTY/100.0*assignment.max_score * (delta+1)))
                            log(f"Late penalty: {GRADE - NEW_GRADE} points", type="warning")
                            log(f"New grade after applying late penalty: {NEW_GRADE}", type="warning")
                            GRADE = NEW_GRADE

                    else:
                        log("This assignment has no due date.")
                else:
                    log(f"Failed to retrieve assignment. Status Code: {response.status_code} Response: {response.text}", type="error")
                    canvas_submissoin_status = False
                    continue

                if submission_response.status_code == 200:
                    submission = submission_response.json()
                    if RUBRIC_CRITERION is None:
                        grade_value = submission.get('grade')
                        previous_grade = float(grade_value) if grade_value is not None else 0.0 
                    else:
                        # If rubric criterion is specified, get the grade from the rubric
                        rubric = submission.get('rubric_assessment', {})
                        criterion = rubric.get(RUBRIC_CRITERION, {})
                        grade_value = criterion.get('points', 0.0)
                        previous_grade = float(grade_value) if grade_value is not None else 0.0
                    log(f"Previous submission grade: {previous_grade}")
                else:
                    log(f"Failed to retrieve previous submission. Status Code: {response.status_code} Response: {response.text}", type="warning")
                    previous_grade = 0

                if previous_grade is not None and previous_grade > GRADE:
                    log(f"Previous grade {previous_grade} is higher than the new grade {GRADE}. NOT posting the new grade.", type="warning")
                    continue

                # -------------------------------
                # Post grade
                # -------------------------------

                # API Endpoint
                url = f"{API_URL}/courses/{COURSE_ID}/assignments/{ASSIGNMENT_ID}/submissions/{STUDENT_ID}"

                # Headers
                headers = {
                    'Authorization': f'Bearer {API_TOKEN}',
                    'Content-Type': 'application/json'
                }

                if RUBRIC_CRITERION is None:
                    # Payload
                    payload = {
                        'submission': {
                            'posted_grade': GRADE
                        },
                        'comment': {
                            'text_comment': f"Grade posted via AutoGrader on {self.dtStylish(datetime.now(), '%A, %B {th}, %Y at %H:%M:%S')}.",
                        }
                    }
                else:
                    rubric = submission.get("rubric_assessment", {})
                    rubric[RUBRIC_CRITERION] = {"points": NEW_GRADE, "comments": f"Grade posted via AutoGrader on {self.dtStylish(datetime.now(), '%A, %B {th}, %Y at %H:%M:%S')}."}
                    score_list = [criterion.get("points", None) for criterion in rubric.values()]
                    # Check if there is a missing score in score_list
                    if any(s is None for s in score_list):
                        payload = {
                                'rubric_assessment': rubric
                        }
                    else:
                        TOTAL_SCORE = sum(score_list)
                        payload = {
                                'posted_grade': TOTAL_SCORE,
                                'rubric_assessment': rubric
                        }

                # POST Request
                response = requests.put(url, headers=headers, json=payload)

                # Response Check
                if response.status_code == 200:
                    log(f"✅ Grade successfully posted.")
                else:
                    log(f"Failed to post grade. Status Code: {response.status_code} Response: {response.text}", type="error")
                    canvas_submissoin_status = False
            
            # Pull request comment footer
            self.format_markdown_footer(canvas_submissoin_status=canvas_submissoin_status)

        @staticmethod
        def dtStylish(dt,f):
            ordinal = str(dt.day)+("th" if 4<=dt.day%100<=20 else {1:"st",2:"nd",3:"rd"}.get(dt.day%10, "th"))
            return dt.strftime(f).replace("{th}", ordinal)

        @staticmethod
        def rgb_to_hex(r, g, b):
            """
            Converts RGB color values to a hexadecimal string.

            Args:
                r (int): Red component (0-255).
                g (int): Green component (0-255).
                b (int): Blue component (0-255).

            Returns:
                str: Hexadecimal color string (e.g., '#RRGGBB').
            """
            # Ensure values are within the valid range (0-255)
            r = max(0, min(255, r))
            g = max(0, min(255, g))
            b = max(0, min(255, b))

            # Use f-strings for concise formatting (Python 3.6+)
            return f'#{r:02X}{g:02X}{b:02X}'

        @staticmethod
        def save_data_to_pkl(class_inputs: dict[str, dict | np.ndarray],
                               input_sets: list[dict[str, np.ndarray]], 
                               output_sets: list[dict[str, np.ndarray]], 
                               data_file: str):
            """
            Save the data to pickle file.
            """

            # Combine the information into a single dictionary
            combined_data = {
                "class_inputs": class_inputs,
                "input_sets": input_sets,
                "output_sets": output_sets
            }

            # Save the combined data to a pickle file
            with open(data_file, "wb") as f:
                pickle.dump(combined_data, f)

        @staticmethod
        def generate_random_input(shape: tuple, ranges: np.ndarray) -> np.ndarray:
            if ranges.shape[0:len(shape)] != shape:
                log(f"Input shape {shape} does not match ranges shape {ranges.shape}.", type="error")
            low = ranges[...,0]
            high = ranges[...,1]
            return np.random.uniform(low, high)

        @staticmethod
        def load_data_from_pkl(data_file: str, required_modules) -> tuple[dict[str, np.ndarray],list[dict[str, np.ndarray]],list[dict[str, np.ndarray]]]:
            """
            Load pickle file data

            Args:
                data_file: path to pickle file

            Returns:
                class_inputs: dict, maps input keyword (i.e. a label) to np.ndarray of correct shape
                input_sets: list of dicts, each dict maps input keyword (i.e. a label) to np.ndarray of correct shape
                output_sets: list of dicts, each dict maps output keyword (i.e. a label) to np.ndarray of correct shape
            """

            # Load the data from the pickle file
            try:
                if required_modules:
                    for module in required_modules:
                        importlib.import_module(module)

                with open(data_file, "rb") as f:
                    data = pickle.load(f)
            except FileNotFoundError:
                log(f"Pickel file {data_file} not found. Please ensure the file exists and is in the correct format.", type="error")
                return {}, [], []
            
            # Confrim the data is formatted correctly
            if not all(key in data for key in ["class_inputs", "input_sets", "output_sets"]):
                log(f"Data file {data_file} is in the wrong format. Expected keys: 'class_inputs', 'input_sets', 'output_sets'. Found keys: {data.keys()}", type="error")
                return {}, [], []
            
            # Unpack the data
            class_inputs = data.get("class_inputs", {})
            input_sets = data.get("input_sets", [])
            output_sets = data.get("output_sets", [])

            return class_inputs, input_sets, output_sets

        @staticmethod
        def create_auto_grader_files(repo_name: str = None, overwrite: bool = False):
            """
            Create the necessary files for the auto grader to work.
            This includes the private grader folder and the roster file.
            """

            # Warn students not to use this method
            log("This method is not for students. It will override important autograding files with junk data. If you accidentally run it then you need to use git to reset those files.", type="warning")

            # Get the current file path
            auto_grader_path = os.path.dirname(os.path.abspath(__file__))
            root_file_path = os.path.dirname(auto_grader_path)
            if repo_name is None:
                root_folder_name = os.path.basename(root_file_path)
            else:
                root_folder_name = repo_name
            private_data_folder = "_" + root_folder_name + "_private_data"
            public_data_folder = root_folder_name + "_public_data"
            private_data_path = os.path.join(root_file_path, private_data_folder)
            public_data_path = os.path.join(root_file_path, public_data_folder)
            workflow_file_path = os.path.join(root_file_path, ".github", "workflows")

            # ---------------------------------------------------------------
            # Create the private grader folder and files
            # ---------------------------------------------------------------

            # Create the private grader folder if it does not exist
            if not os.path.exists(private_data_path):
                os.makedirs(private_data_path)
            if not os.path.exists(public_data_folder):
                os.makedirs(public_data_folder)

            # Create the roster file if it does not exist
            roster_file = os.path.join(private_data_folder, "_roster.csv")
            if not os.path.exists(roster_file) or overwrite:
                with open(roster_file, "w") as f:
                    print("github_username,canvas_student_id", file=f)
            
            # ---------------------------------------------------------------
            # Create the root folder and files
            # ---------------------------------------------------------------

            # Create the generator file if it does not exist
            gen_file = os.path.join(root_file_path, "_create_assignment_files.py")
            if not os.path.exists(gen_file) or overwrite:
                with open(gen_file, "w") as f:
                    print("from DNE_assignment_info import auto_grader", file=f)
                    print("auto_grader.create_assignment_files()", file=f)

            # Create the post grades file if it does not exist
            post_file = os.path.join(root_file_path, "DNE_github_grade_on_push.py")
            if not os.path.exists(post_file) or overwrite:
                with open(post_file, "w") as f:
                    for line in AutoGrader.DNE_text:
                        print(line, file=f)
                    print("from DNE_assignment_info import auto_grader", file=f)
                    print("auto_grader.post_grades()", file=f)
                    for line in AutoGrader.DNE_text:
                        print(line, file=f)

            # Initilize the assignment info file if it does not exist
            assignment_info_template_file = os.path.join(auto_grader_path, "DNE_assignment_info_template.py")
            assignment_info_file = os.path.join(root_file_path, "DNE_assignment_info.py")
            if not os.path.exists(assignment_info_file) or overwrite:
                shutil.copy(assignment_info_template_file, assignment_info_file)

            # Initilize the workflow file if it does not exist
            provided_file = os.path.join(auto_grader_path, "DNE_classroom_template.yml")
            installed_file = os.path.join(workflow_file_path, "classroom.yml")
            if not os.path.exists(workflow_file_path):
                os.makedirs(workflow_file_path)
            if not os.path.exists(installed_file) or overwrite:
                shutil.copy(provided_file, installed_file)

            # Initilize the requirements file if it does not exist
            provided_file = os.path.join(auto_grader_path, "DNE_requirements_template.txt")
            installed_file = os.path.join(root_file_path, "requirements.txt")
            if not os.path.exists(installed_file) or overwrite:
                shutil.copy(provided_file, installed_file)
            
########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################