########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
# 
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################

import os

# Logging parameters
print_to_log_file = True
print_to_console = True
print_info = True
print_debug = True
print_warning = True
print_error = True
print_grade = True
print_break = True

def log(message: str, type: str = "info"):
    """
    Print a debug or error message to the log.
    Use traceback.format_exc() to get the error as a string.
    """

    if print_to_log_file:
        to_print = False
        if type == "info":
            type = "ℹ️ Info"
            if print_info:
                to_print = True
        elif type == "debug":
            type = "🐛 Debug"
            if print_debug:
                to_print = True
        elif type == "warning":
            type = "⚠️ WARNING"
            if print_warning:
                to_print = True
        elif type == "error":
            type = "❌ ERROR"
            if print_error:
                to_print = True
        elif type == "grade":
            type = "📝 Grade"

            if message < 100:
                message = "❌ " + str(message)
            else:
                message = "✅ " + str(message)

            if print_grade:
                to_print = True
        elif type == "break":
            type = "↓"*100
            if print_break:
                to_print = True
        else:
            log(f"Unknown log type: {type}. Defaulting to 'info'.", type="warning")
            type = "ℹ️ Info"
            if print_info:
                to_print = True
            
        
        message = f"{type}: {message}"

        if to_print and print_to_console:
            print(message)
        
        if to_print and print_to_log_file:

            # Define the maximum number of lines to keep in the log
            max_lines = 1000  # Maximum number of lines to keep in the log

            # get file path
            current_file_path = os.path.abspath(__file__)
            current_dir = os.path.dirname(current_file_path)
            filepath = os.path.join(current_dir,"_log.txt")

            # Get the current log file content
            lines = []
            try:
                with open(filepath, 'r') as f:
                    lines = f.readlines()
            except FileNotFoundError:
                pass

            # Add the new message to the log
            lines.append(message + "\n")

            # Truncate if exceeding max_lines
            if len(lines) > max_lines:
                lines = lines[-max_lines:]  # Keep only the latest 'max_lines'
                
            # Write the (potentially truncated) lines back to the file
            with open(filepath, 'w') as f:
                f.writelines(lines)

# Mark the begining of a logging session
log("", type="break")

########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
# 
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################