########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
# 
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################

class Assignment:
    def __init__(self, title, id, input_shapes, output_shapes, input_ranges, input_labels, output_labels, function_to_evaluate, class_to_evaluate=None, class_inputs=None, max_score=100.0, iterations=int(1e4)):
        self.title = title
        self.id = id
        self.input_shapes = input_shapes
        self.output_shapes = output_shapes
        self.input_ranges = input_ranges
        self.input_labels = input_labels
        self.output_labels = output_labels
        self.function_to_evaluate = function_to_evaluate
        self.class_to_evaluate = class_to_evaluate
        self.class_inputs = class_inputs
        self.max_score = max_score
        self.iterations = iterations

########################################################################################
# 
#  ____    ___        _   _   ___   _____       _____  ____   _ __  _____ 
# |  _ \  / _ \      | \ | | / _ \ |_   _|     | ____||  _ \ |_  _||_   _|
# | | | || | | |     |  \| || | | |  | |       |  _|  | | | | |  |   | |  
# | |_| || |_| |     | |\  || |_| |  | |       | |___ | |_| | |  |   | |  
# |____/  \___/      |_| \_| \___/   |_|       |_____||____/ |_ __|  |_|  
# 
#
# Do not edit this file. It is part of the system that grades your code submisions.
# The instructor will be notified if you submit an edited version of this file.
########################################################################################